<?php
/** @var ADM\QuickDevBar\Block\Tab\Content\Sql $block */
if ($block->hasProfiler()): ?>
    <div id="sql_stats">
    </div>
    <div id="sql_queries" style="max-height: 500px; overflow:auto; box-shadow: 0 0 5px rgba(0,0,0,.5) inset;">
    </div>
    <br/>
    <div class="control">
        <label for="sql_profiles">Request</label>
        <select id="sql_profiles" name="sql-profile">
        </select>
    </div>
    <br/>
    <div class="control">
        <label for="sql_aggregations">Aggregation</label>
        <select id="sql_aggregations" name="sql-aggregation">
        </select>
    </div>
    <br/>
    <button id="clear" type="button" class="qdb-action">Clear all Requests</button>
    <script type="text/javascript">
        require([
            'quickDevBarSql'
        ]);
    </script>
<?php
else: ?>
    SQL profiler is not active<br/>
    You should set a new key for $config array in file app/etc/env.php<br/>
    <pre>$config[db][connection][default][profiler] = 1</pre>
<?php
endif ?>
